dist: trusty
sudo: false

language: python
python:
  - 2.7
  - 3.6
matrix:
  fast_finish: true

cache:
  ccache: true
  apt: true
  directories:
    - $HOME/.cache/pip

before_install:
  - pip install -U pip

install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install -e .
  - pip install pylint
  - pip freeze

script:
  - py.test -vv -x --durations=20 ./tests
  - pylint okcompute --disable=R,C
